### ISSUE TITLE
Could not connect to Clickhouse.

### ISSUE THREAD

**Issue by dpkrane** [caioricciuti/ch-ui#16] opened 2024-09-12 07:33 UTC
### Environment

Docker

### How did you encounter the bug?

1. Run docker with docker run -p 5521:5521 \
  -e VITE_CLICKHOUSE_URL=http://my-clickhouse-server:8123 \
  -e VITE_CLICKHOUSE_USER=my-username \
  -e VITE_CLICKHOUSE_PASS=my-password \
  ghcr.io/caioricciuti/ch-ui:latest
2. Get Ch-UI in browser at http://localhost:5521/
3. Try to connect
4. Fail...

### What did you expect?

I try to connect.

### Actual Result

![CleanShot 2024-09-12 at 10 25 01@2x](https://github.com/user-attachments/assets/d4140a83-3b1b-4d1f-95be-d27878211f1c)
But
```bash
➜ curl -i 'http://192.168.3.23:8123/?query_id=1acf1ffd-da58-4558-b590-f0b7a5f9fe74' \
  -H 'Referer: http://localhost:5521/' \
  -H 'Authorization: Basic Y2xpY2tob3VzZTp6bGYzNHZqX2ZqIw==' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36' \
  -H 'Content-Type: text/plain;charset=UTF-8' \
  --data-raw $'SELECT version() \nFORMAT JSONEachRow'
HTTP/1.1 200 OK
Date: Thu, 12 Sep 2024 07:26:54 GMT
Connection: Keep-Alive
Content-Type: application/x-ndjson; charset=UTF-8
X-ClickHouse-Server-Display-Name: db1.kinoplan24.ru
Transfer-Encoding: chunked
X-ClickHouse-Query-Id: 1acf1ffd-da58-4558-b590-f0b7a5f9fe74
X-ClickHouse-Format: JSONEachRow
X-ClickHouse-Timezone: UTC
Keep-Alive: timeout=3
X-ClickHouse-Summary: {"read_rows":"1","read_bytes":"1","written_rows":"0","written_bytes":"0","total_rows_to_read":"0","result_rows":"0","result_bytes":"0","elapsed_ns":"40642130"}

{"version()":"23.12.2.59"}
```
![CleanShot 2024-09-12 at 10 29 01@2x](https://github.com/user-attachments/assets/4117a4e8-bbbf-447b-9fc1-7452c9cf339d)

http://192.168.3.23:8123/play accessed too.

**Comment by caioricciuti** [comment] 2024-09-12 07:36
Hey, this is a possible duplicate of: #8 can you please try the solution I've given there?

**Comment by dpkrane** [comment] 2024-09-12 08:58
> Hey, this is a possible duplicate of: #8 can you please try the solution I've given there?

10x for quick responce.
CORS settings exist.

In Clickhouse error log I see
```
2024.09.12 08:55:52.867800 [ 89034 ] {} <Warning> HTTPServerRequest: Got an HTTP request with no content length and no chunked/multipart encoding, it may be impossible to distinguish graceful EOF from abnormal connection loss (skipped 1 similar messages)
2024.09.12 08:56:03.190805 [ 89034 ] {} <Warning> HTTPServerRequest: Got an HTTP request with no content length and no chunked/multipart encoding, it may be impossible to distinguish graceful EOF from abnormal connection loss (skipped 1 similar messages)

```

**Comment by caioricciuti** [comment] 2024-09-12 18:34
Can you try to use the files `user.xml` and `config.xml` that I shared on #8 and test it? 

I've tested with those and works, and the error I get when I don't use is the same you're seeing on your instance...

**Comment by caioricciuti** [comment] 2024-09-16 07:53
I'll close this issue, if you have any feedback please let me know, I've tested again with the solution on #8 and it worked (using both `config.xml` and `users.xml`. If needed re-open the issue...

**Closed by caioricciuti** 2024-09-16 07:53 UTC
